name: "Buildability and Sanity"
on:
  push:
    branches:
      - wasm
      - master
      - '*'
      - '!libretro'

env:
  EM_VERSION: 3.1.53
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  sanity:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-20.04]
        cc: [gcc, clang]
        include:
        - os: macos-latest
          cc: clang
          extra_targets: cocoa ios-ipa ios-deb
        exclude:
        - os: macos-latest
          cc: gcc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        shell: bash
        run: |
          ./.github/actions/install_deps.sh ${{ matrix.os }}
      - name: Build
        run: |
          ${{ matrix.cc }} -v; (make -j all CONF=release CC=${{ matrix.cc }} || (echo "==== Build Failed ==="; make all CONF=release CC=${{ matrix.cc }}))
      - name: Sanity tests
        shell: bash
        run: |
          ./.github/actions/sanity_tests.sh
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: sameboy-canary-${{ matrix.os }}-${{ matrix.cc }}
          path: |
            build/bin
            build/lib
            build/include

  wasm:
    runs-on: ubuntu-latest
    needs: sanity
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        shell: bash
        run: |
          ./.github/actions/install_deps.sh ubuntu
      - name: Setup emscripten cache
        id: cache-system-libraries
        uses: actions/cache@v3
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - name: Setup emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Build WASM
        run: |
          make -C wasm bootroms
          make -j $(nproc) wasm CONF=release
      - name: Publish WASM binaries
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/wasm_bin
